openapi: 3.2.0
info:
  title: Toqio Integration Hub Lending - Loan - Request API
  version: v0
servers:
- url: https://your_connector_url
  description: This is an example url that you could use for testing purposes as this documentation describes the API that you must develop in your connector.
security:
- bearerAuth: []
tags:
- name: Lending - Loan - Request
paths:
  /customers/{customerId}/lending/requests:
    post:
      tags:
      - Lending - Loan - Request
      summary: Create a lending request
      description: ''
      operationId: createLendingRequest
      parameters:
      - name: customerId
        in: path
        description: Customer ID. Cannot be null or empty.
        required: true
        schema:
          type: string
      - name: lendingRequestRequest
        in: query
        description: Lending request request. Cannot be null.
        required: true
        schema:
          $ref: '#/components/schemas/LendingRequestBaseRequest'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LendingRequestBaseRequest'
        required: true
      responses:
        '200':
          description: Lending request created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ToqioHttpOkLendingRequestBaseResponse'
        '400':
          description: Invalid request
        '500':
          description: Internal server error
  /customers/{customerId}/lending/requests/{lendingRequestId}:
    get:
      tags:
      - Lending - Loan - Request
      summary: Get a lending request
      description: ''
      operationId: getLendingRequest
      parameters:
      - name: customerId
        in: path
        description: Customer ID. Cannot be null or empty.
        required: true
        schema:
          type: string
      - name: lendingRequestId
        in: path
        description: Lending request ID. Cannot be null or empty.
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Lending request retrieved
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ToqioHttpOkLendingRequestBaseResponse'
        '400':
          description: Invalid request
        '500':
          description: Internal server error
    put:
      tags:
      - Lending - Loan - Request
      summary: Update a lending request
      description: ''
      operationId: updateLendingRequest
      parameters:
      - name: customerId
        in: path
        description: Customer ID. Cannot be null or empty.
        required: true
        schema:
          type: string
      - name: lendingRequestId
        in: path
        description: Lending request ID. Cannot be null or empty.
        required: true
        schema:
          type: string
      - name: lendingRequestRequest
        in: query
        description: Lending request request. Cannot be null.
        required: true
        schema:
          $ref: '#/components/schemas/LendingRequestBaseRequest'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LendingRequestBaseRequest'
        required: true
      responses:
        '200':
          description: Lending request updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ToqioHttpOkLendingRequestBaseResponse'
        '400':
          description: Bad request
        '500':
          description: Internal server error
  /customers/{customerId}/lending/requests/find:
    post:
      tags:
      - Lending - Loan - Request
      summary: Get lending requests by filter
      description: ''
      operationId: getLendingRequestsByFilter
      parameters:
      - name: customerId
        in: path
        description: Customer ID. Cannot be null or empty.
        required: true
        schema:
          type: string
      - name: lendingRequestFilter
        in: query
        description: Lending request filter. Cannot be null.
        required: true
        schema:
          $ref: '#/components/schemas/LendingRequestFilter'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LendingRequestFilter'
        required: true
      responses:
        '200':
          description: Lending requests retrieved
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ToqioHttpOkLendingRequestBaseResponse'
        '400':
          description: Invalid request
        '500':
          description: Internal server error
components:
  schemas:
    AccountInformation:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        currencyISOCode:
          type: string
        accountNumber:
          type: string
        sortCode:
          type: string
        iban:
          type: string
        bic:
          type: string
    Phone:
      type: object
      properties:
        phoneNumber:
          type: string
        countryISOCode:
          type: string
        intnlPhoneNumber:
          type: string
    SignificantPerson:
      type: object
      properties:
        id:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        type:
          type: string
          enum:
          - DIRECTOR
          - SHAREHOLDER
          - BENEFICIAL_OWNER
        address:
          type: string
        dateOfBirth:
          type: string
        emailAddress:
          type: string
        phone:
          $ref: '#/components/schemas/Phone'
        nationality:
          type: string
        documentNumber:
          type: string
    LendingRequestFilter:
      type: object
      properties:
        productType:
          type: string
          enum:
          - CASH_ADVANCE
          - SHORT_TERM_LOAN
        status:
          type: string
          enum:
          - CREATED
          - SUBMITTED
          - APPROVED
          - REJECTED
          - MORE_INFORMATION_REQUIRED
          - CANCELLED
          - LOAN_OFFER_PROVIDED
          - LOAN_OFFER_ACCEPTED
          - LOAN_OFFER_CANCELLED
          - CONTRACT_SIGNED
        merchantId:
          type: string
    MerchantInformation:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        type:
          type: string
          enum:
          - BUSINESS
          - CONSUMER
        countryISOCode:
          type: string
        registeredAddress:
          type: string
        monthsTrading:
          type: string
        keyContactName:
          type: string
        keyContactPhoneNumber:
          $ref: '#/components/schemas/Phone'
        keyContactEmailAddress:
          type: string
        significantPeople:
          type: array
          items:
            $ref: '#/components/schemas/SignificantPerson'
        sales:
          $ref: '#/components/schemas/Document'
    ToqioHttpOkLendingRequestBaseResponse:
      type: object
      properties:
        data:
          $ref: '#/components/schemas/LendingRequestBaseRequest'
        code:
          type: string
          example: OK
        errorSeverity:
          type: string
          example: NONE
        message:
          type: string
          example: Ok
        httpStatus:
          type: integer
          format: int32
          example: 200
        requestId:
          type: string
          example: 26b0f78a-79f9-426d-a20b-79841345ae51
        date:
          type: string
          example: '2024-08-01T00:00:00.000Z'
    LoanInformation:
      type: object
      properties:
        amount:
          type: number
          format: double
        currencyISOCode:
          type: string
        purpose:
          type: string
        maturity:
          type: integer
          format: int32
        productType:
          type: string
          enum:
          - CASH_ADVANCE
          - SHORT_TERM_LOAN
        documents:
          type: array
          items:
            $ref: '#/components/schemas/Document'
        preferredRepaymentTerms:
          type: number
          format: double
    LendingRequestBaseRequest:
      type: object
      properties:
        creditCheckPermission:
          type: boolean
        dataPrivacyConsent:
          type: boolean
        loan:
          $ref: '#/components/schemas/LoanInformation'
        account:
          $ref: '#/components/schemas/AccountInformation'
        merchant:
          $ref: '#/components/schemas/MerchantInformation'
        submissionDate:
          type: string
    Document:
      type: object
      properties:
        base64:
          type: string
        name:
          type: string
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
x-source-pages:
- https://integrate.toq.io/reference/acceptloanoffer-1
- https://integrate.toq.io/reference/applydirectdebit-1
- https://integrate.toq.io/reference/createaccount-1
- https://integrate.toq.io/reference/createbeneficiary-1
- https://integrate.toq.io/reference/createcustomer-1
- https://integrate.toq.io/reference/createlenderconfiguration-1
- https://integrate.toq.io/reference/createlendingrequest-1
- https://integrate.toq.io/reference/createmerchant-1
- https://integrate.toq.io/reference/deleteaccount-1
- https://integrate.toq.io/reference/deletebeneficiary-1
- https://integrate.toq.io/reference/deletemeawalletapiconfig-1
- https://integrate.toq.io/reference/fetchtransactions-1
- https://integrate.toq.io/reference/findaccounttransactionliststatement
- https://integrate.toq.io/reference/findaccounttransactionliststatement_1
- https://integrate.toq.io/reference/findbeneficiary-1
- https://integrate.toq.io/reference/findcustomer-1
- https://integrate.toq.io/reference/getaccount-1
- https://integrate.toq.io/reference/getaccountownershipcertificate-1
- https://integrate.toq.io/reference/getaccounts-1
- https://integrate.toq.io/reference/getassettypes-1
- https://integrate.toq.io/reference/getbankpaymentschemes-1
- https://integrate.toq.io/reference/getbankstatementfooter-1
- https://integrate.toq.io/reference/getbeneficiary-1
- https://integrate.toq.io/reference/getbeneficiaryfilters-1
- https://integrate.toq.io/reference/getbillingcurrencies-1
- https://integrate.toq.io/reference/getcapabilities-1
- https://integrate.toq.io/reference/getcompany-1
- https://integrate.toq.io/reference/getcontract-1
- https://integrate.toq.io/reference/getcustomerconnectionstatus-1
- https://integrate.toq.io/reference/getdefaultrepaymentterms-1
- https://integrate.toq.io/reference/getdynamicaccountbalances
- https://integrate.toq.io/reference/getdynamicbuttonconfiguration-1
- https://integrate.toq.io/reference/getlenderconfiguration-1
- https://integrate.toq.io/reference/getlendingrequest-1
- https://integrate.toq.io/reference/getlendingrequestsbyfilter-1
- https://integrate.toq.io/reference/getloan-1
- https://integrate.toq.io/reference/getloanoffer-1
- https://integrate.toq.io/reference/getloansbyfilter-1
- https://integrate.toq.io/reference/getloantransactions-1
- https://integrate.toq.io/reference/getmandatedetail-1
- https://integrate.toq.io/reference/getmandates-1
- https://integrate.toq.io/reference/getmeawalletapiconfig-1
- https://integrate.toq.io/reference/getpartnerproducts-1
- https://integrate.toq.io/reference/getpaymentoptions
- https://integrate.toq.io/reference/getproviderpartnerproducts-1
- https://integrate.toq.io/reference/getquoteforcurrencypair-1
- https://integrate.toq.io/reference/gettransactionstatus-1
- https://integrate.toq.io/reference/hostedonboarding-1
- https://integrate.toq.io/reference/notifycustomnotificationerrors-1
- https://integrate.toq.io/reference/notifyproductchanges
- https://integrate.toq.io/reference/resendotp-1
- https://integrate.toq.io/reference/savetransfer-1
- https://integrate.toq.io/reference/searchbeneficiaries-1
- https://integrate.toq.io/reference/sendemailnotification-1
- https://integrate.toq.io/reference/synctransactions-1
- https://integrate.toq.io/reference/synctransactionstatus-1
- https://integrate.toq.io/reference/synctransactionstatus_1-1
- https://integrate.toq.io/reference/updateaccount-1
- https://integrate.toq.io/reference/updatebeneficiary-1
- https://integrate.toq.io/reference/updateenduser-1
- https://integrate.toq.io/reference/updateenduserdirectors-1
- https://integrate.toq.io/reference/updatelenderconfiguration-1
- https://integrate.toq.io/reference/updatelendingrequest-1
- https://integrate.toq.io/reference/updatemeawalletapiconfig-1
- https://integrate.toq.io/reference/validatecompany-1
- https://integrate.toq.io/reference/verifybeneficiarycompany
- https://integrate.toq.io/reference/webhook_3-1
- https://integrate.toq.io/reference/webhook_4-1
