openapi: 3.2.0
info:
  title: Toqio Integration Hub Lending API
  version: v0
servers:
- url: https://your_connector_url
  description: This is an example url that you could use for testing purposes as this documentation describes the API that you must develop in your connector.
security:
- bearerAuth: []
tags:
- name: Lending
paths:
  /customers/{customerId}/lending/default-repayment-terms:
    get:
      tags:
      - Lending
      summary: Get default repayment terms
      description: ''
      operationId: getDefaultRepaymentTerms
      parameters:
      - name: customerId
        in: path
        description: Customer ID. Cannot be null or empty.
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Default repayment terms retrieved
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ToqioHttpOkDefaultRepaymentTermsResponse'
        '400':
          description: Invalid request
        '500':
          description: Internal server error
components:
  schemas:
    ToqioHttpOkDefaultRepaymentTermsResponse:
      type: object
      properties:
        data:
          $ref: '#/components/schemas/DefaultRepaymentTerms'
        code:
          type: string
          example: OK
        errorSeverity:
          type: string
          example: NONE
        message:
          type: string
          example: Ok
        httpStatus:
          type: integer
          format: int32
          example: 200
        requestId:
          type: string
          example: 26b0f78a-79f9-426d-a20b-79841345ae51
        date:
          type: string
          example: '2024-08-01T00:00:00.000Z'
    DefaultRepaymentTerms:
      type: object
      properties:
        minDailyPercentage:
          type: number
          format: double
        maxDailyPercentage:
          type: number
          format: double
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
x-source-pages:
- https://integrate.toq.io/reference/acceptloanoffer-1
- https://integrate.toq.io/reference/applydirectdebit-1
- https://integrate.toq.io/reference/createaccount-1
- https://integrate.toq.io/reference/createbeneficiary-1
- https://integrate.toq.io/reference/createcustomer-1
- https://integrate.toq.io/reference/createlenderconfiguration-1
- https://integrate.toq.io/reference/createlendingrequest-1
- https://integrate.toq.io/reference/createmerchant-1
- https://integrate.toq.io/reference/deleteaccount-1
- https://integrate.toq.io/reference/deletebeneficiary-1
- https://integrate.toq.io/reference/deletemeawalletapiconfig-1
- https://integrate.toq.io/reference/fetchtransactions-1
- https://integrate.toq.io/reference/findaccounttransactionliststatement
- https://integrate.toq.io/reference/findaccounttransactionliststatement_1
- https://integrate.toq.io/reference/findbeneficiary-1
- https://integrate.toq.io/reference/findcustomer-1
- https://integrate.toq.io/reference/getaccount-1
- https://integrate.toq.io/reference/getaccountownershipcertificate-1
- https://integrate.toq.io/reference/getaccounts-1
- https://integrate.toq.io/reference/getassettypes-1
- https://integrate.toq.io/reference/getbankpaymentschemes-1
- https://integrate.toq.io/reference/getbankstatementfooter-1
- https://integrate.toq.io/reference/getbeneficiary-1
- https://integrate.toq.io/reference/getbeneficiaryfilters-1
- https://integrate.toq.io/reference/getbillingcurrencies-1
- https://integrate.toq.io/reference/getcapabilities-1
- https://integrate.toq.io/reference/getcompany-1
- https://integrate.toq.io/reference/getcontract-1
- https://integrate.toq.io/reference/getcustomerconnectionstatus-1
- https://integrate.toq.io/reference/getdefaultrepaymentterms-1
- https://integrate.toq.io/reference/getdynamicaccountbalances
- https://integrate.toq.io/reference/getdynamicbuttonconfiguration-1
- https://integrate.toq.io/reference/getlenderconfiguration-1
- https://integrate.toq.io/reference/getlendingrequest-1
- https://integrate.toq.io/reference/getlendingrequestsbyfilter-1
- https://integrate.toq.io/reference/getloan-1
- https://integrate.toq.io/reference/getloanoffer-1
- https://integrate.toq.io/reference/getloansbyfilter-1
- https://integrate.toq.io/reference/getloantransactions-1
- https://integrate.toq.io/reference/getmandatedetail-1
- https://integrate.toq.io/reference/getmandates-1
- https://integrate.toq.io/reference/getmeawalletapiconfig-1
- https://integrate.toq.io/reference/getpartnerproducts-1
- https://integrate.toq.io/reference/getpaymentoptions
- https://integrate.toq.io/reference/getproviderpartnerproducts-1
- https://integrate.toq.io/reference/getquoteforcurrencypair-1
- https://integrate.toq.io/reference/gettransactionstatus-1
- https://integrate.toq.io/reference/hostedonboarding-1
- https://integrate.toq.io/reference/notifycustomnotificationerrors-1
- https://integrate.toq.io/reference/notifyproductchanges
- https://integrate.toq.io/reference/resendotp-1
- https://integrate.toq.io/reference/savetransfer-1
- https://integrate.toq.io/reference/searchbeneficiaries-1
- https://integrate.toq.io/reference/sendemailnotification-1
- https://integrate.toq.io/reference/synctransactions-1
- https://integrate.toq.io/reference/synctransactionstatus-1
- https://integrate.toq.io/reference/synctransactionstatus_1-1
- https://integrate.toq.io/reference/updateaccount-1
- https://integrate.toq.io/reference/updatebeneficiary-1
- https://integrate.toq.io/reference/updateenduser-1
- https://integrate.toq.io/reference/updateenduserdirectors-1
- https://integrate.toq.io/reference/updatelenderconfiguration-1
- https://integrate.toq.io/reference/updatelendingrequest-1
- https://integrate.toq.io/reference/updatemeawalletapiconfig-1
- https://integrate.toq.io/reference/validatecompany-1
- https://integrate.toq.io/reference/verifybeneficiarycompany
- https://integrate.toq.io/reference/webhook_3-1
- https://integrate.toq.io/reference/webhook_4-1
